export default {

  /********************* BottomTabs  Icons **********************/ 
  firstActiveIcon: require('../assets/images/ic_blue_setting.png'),
  firstInActiveIcon: require('../assets/images/ic_blue_setting.png'),
  secondActiveIcon: require('../assets/images/ic_blue_setting.png'),
  secondInActiveIcon: require('../assets/images/ic_blue_setting.png'),
  thirdActiveIcon: require('../assets/images/ic_blue_setting.png'),
  thirdInActiveIcon: require('../assets/images/ic_blue_setting.png'),
  fourthActiveIcon: require('../assets/images/ic_blue_setting.png'),
  fourthInActiveIcon: require('../assets/images/ic_blue_setting.png'),
  fifthActiveIcon: require('../assets/images/ic_blue_setting.png'),
  fifthInActiveIcon: require('../assets/images/ic_blue_setting.png'),
  ic_back: require('../assets/images/ic_back.png'),
  house: require('../assets/images/house.png'),
  offer: require('../assets/images/offer.png'),
  privacy: require('../assets/images/privacy.png'),
  faq: require('../assets/images/faq.png'),
  history: require('../assets/images/history.png'),
  logout: require('../assets/images/logout.png'),
  terms: require('../assets/images/terms.png'),
  img1: require('../assets/images/img1.jpeg'),
  img2: require('../assets/images/img2.jpeg'),
  img3: require('../assets/images/img3.jpeg'),
  img4: require('../assets/images/img4.jpeg'),
  img5: require('../assets/images/img5.jpeg'),
  img6: require('../assets/images/img6.jpeg'),
  img7: require('../assets/images/img7.jpeg'),
  img8: require('../assets/images/img8.jpeg'),
  img9: require('../assets/images/img9.jpeg'),
  img10: require('../assets/images/img10.jpeg'),
  person1: require('../assets/images/person1.jpeg'),
  person2: require('../assets/images/person2.jpeg'),
  person3: require('../assets/images/person3.jpeg'),
  person4: require('../assets/images/person4.jpeg'),
  person5: require('../assets/images/person5.jpeg'),
  person6: require('../assets/images/person6.jpeg'),
  person7: require('../assets/images/person7.jpeg'),
  person8: require('../assets/images/person8.jpeg'),
  person9: require('../assets/images/person9.jpeg'),
};
